export const encouragingPhrases = [
  "You are loved.",
  "You've got this!",
  "Believe in yourself.",
  "Keep going!",
  "Don't give up.",
  "Stay positive.",
  "You're amazing.",
  "Dream big!",
  "Smile often.",
  "You're capable of greatness.",
  "Take one step at a time.",
  "Embrace your uniqueness.",
  "You're stronger than you think.",
  "Follow your heart.",
  "Never stop trying.",
  "You make a difference.",
  "Be kind to yourself.",
  "Today is a new day.",
  "Stay hopeful.",
  "You are enough.",
  "Keep shining.",
  "You're a star.",
  "Celebrate small victories.",
  "Choose happiness.",
  "Your journey matters.",
  "Radiate positivity.",
  "You're a ray of sunshine.",
  "Keep your head up.",
  "You're a warrior.",
  "Find joy in the little things.",
  "Your potential is limitless.",
  "Love yourself first.",
  "Chase your dreams.",
  "Be your own cheerleader.",
  "You are beautiful inside and out.",
  "Keep on being awesome.",
  "Stay true to yourself.",
  "You're a work of art.",
  "Every day is a new beginning.",
  "You've got a heart of gold.",
  "You're a star in the making.",
  "The world needs your light.",
  "You're an inspiration.",
  "Believe in your magic.",
  "Follow your passions.",
  "You're a masterpiece in progress.",
  "Keep your spirits high.",
  "Embrace your quirks.",
  "You're a beacon of hope.",
  "Never stop exploring.",
  "You're a bright spark.",
  "You're a shining star.",
  "Keep being fabulous.",
  "Trust the process.",
  "You're a gem.",
  "Keep reaching for the stars.",
  "You're a one-of-a-kind.",
  "Stay fearless.",
  "You're a force to be reckoned with.",
  "Believe in your dreams.",
  "You're making waves.",
  "Stay true to your heart.",
  "You're a true friend.",
  "Be the sunshine in someone's day.",
  "You're making progress.",
  "Stay wild and free.",
  "You're a rainbow after the storm.",
  "You're a true original.",
  "Stay positive and patient.",
  "You're a breath of fresh air.",
  "Keep spreading joy.",
  "You're a star in the making.",
  "The world is better with you in it.",
  "You're changing lives.",
  "Stay curious.",
  "You're a bright light.",
  "You've got a heart of gold.",
  "Believe in your potential.",
  "You're a treasure.",
  "Keep shining your light.",
  "You're a blessing.",
  "You've got a beautiful soul.",
  "Stay kind-hearted.",
  "You're a ray of sunshine on cloudy days.",
  "Keep dreaming big.",
  "You're a champion.",
  "You've got the power.",
  "Stay humble.",
  "You're a star in the making.",
  "You're unstoppable.",
  "Believe in your strength.",
  "You're a miracle.",
  "Keep being extraordinary.",
  "You've got a lot to offer.",
  "You're a superhero.",
  "Stay passionate.",
  "You're a source of inspiration.",
  "You're a game-changer.",
  "Keep being you.",
];
